GET http://localhost:5000/api/users/

###

GET http://localhost:5000/api/users/profile
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjAwMDU5MzM1NjUiLCJQcm92aW5jZUlkIjoxMzEsIkxPVkRlcGFydG1lbnRJZCI6MTAwODksIlVzZXJMZXZlbElkIjo0LCJQYXNzd29yZCI6IiQyYiQxMCRuY2NzOXQwTlpWazVlRmlzM05GYWh1UnM1Uy5Ka0FUekc0L2M5dmV3MzhiT2E0THlBa2hYUyIsIk5hbWUiOiLYudmE2YoiLCJGYW1pbHkiOiLYsdi22KfZitmKIiwiUGhvbmVOdW1iZXIiOm51bGwsImNyZWF0ZUF0IjoiMjAyMi0wNC0xMlQxMDoxODoyMS42NTdaIiwidXBkYXRlZEF0IjpudWxsLCJpYXQiOjE2NTA4NTk3MTgsImV4cCI6MTY1MDg1OTc0OH0.KEp5rLSn5zH7ru-bD4MMEGD4XqTMCxFVkW7kwlX6vYw

###

POST http://localhost:5000/api/users/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjAwMDU5MzM1NjUiLCJQcm92aW5jZUlkIjoxMzEsIkxPVkRlcGFydG1lbnRJZCI6MTAwODksIlVzZXJMZXZlbElkIjo0LCJQYXNzd29yZCI6IiQyYiQxMCRuY2NzOXQwTlpWazVlRmlzM05GYWh1UnM1Uy5Ka0FUekc0L2M5dmV3MzhiT2E0THlBa2hYUyIsIk5hbWUiOiLYudmE2YoiLCJGYW1pbHkiOiLYsdi22KfZitmKIiwiUGhvbmVOdW1iZXIiOm51bGwsImNyZWF0ZUF0IjoiMjAyMi0wNC0xMlQxMDoxODoyMS42NTdaIiwidXBkYXRlZEF0IjpudWxsLCJpYXQiOjE2NTA3ODcyODV9.esoYoaqoC5kphAFW4paXy2Wl7CYGFywMfuOUvZPd9mA"
}


###

DELETE http://localhost:5000/api/users/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMDMiLCJwcm92aW5jZWlkIjoxMSwiY2l0eWlkIjpudWxsLCJkZXBhcnRtZW50aWQiOm51bGwsInVzZXJMZXZlbElkIjoxLCJwYXNzd29yZCI6IiQyYiQxMCR5bWN6VjM2aDkzeU1YcjcwZGltaTd1d2hxV1FSWHZPWE92S0tqd21xNjNqLlc0amE4bHBTZSIsIm5hbWUiOiJIYXNhbiIsImZhbWlseSI6Ikhhc2FuaSIsInBob25lTnVtYmVyIjoiMDIxMTEwMTIxMTE4IiwiY3JlYXRlQXQiOiIyMDIyLTAzLTE1VDA4OjQxOjUyLjEwN1oiLCJ1cGRhdGVkQXQiOiIyMDIyLTAzLTE1VDA4OjQxOjUyLjEwN1oiLCJpYXQiOjE2NDczNDM3Mzd9.0KZKKW52TWIBvdPxP4dcXRy2F_fIf2SvlvKAQa9uLcQ"
}

###
GET http://localhost:5000/api/users/pageItems:5&pageNum:15

###


POST http://localhost:5000/api/users
Content-Type: application/json

{
        "Id": "0004",
        "provinceId": "011",
        "Password": "123456",
        "Name": "Hasan",
        "Family": "Hasani",
        "PhoneNumber": "021110121118"
}

###


POST http://localhost:5000/api/users/login
Content-Type: application/json

{
        "Id": "0005933565",
        "Password": "0005933565"
}